name: Publish

on: workflow_dispatch

jobs:
  build:

    env:
     PROJECT: './src/CookieConsent.Razor.Net.csproj'
     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore $PROJECT
      
    - name: Build
      run: dotnet build $PROJECT --configuration Release  --no-restore

    - name: Publish
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
